name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'

permissions: read-all

jobs:
  cargo-deny:
    name: cargo-deny (licenses, advisories, bans)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@4d1965c9142484e48d40c19de54b5cba84953a06 # v1.10.0
        with:
          toolchain: stable

      - name: Install cargo-deny
        uses: taiki-e/install-action@4a834f5697a0ae1ac87c08e3389b0e30b3f7f3a9 # v2
        with:
          tool: cargo-deny

      - name: Check licenses, advisories, bans
        run: cargo deny check
